### ISSUE TITLE
VS still doesn't consider errors as errors

### ISSUE THREAD

**Issue by dixonqmg** [jwt27/gcc2vs#1]
Hi,

I made this tool work with our build system, and there's still one problem left. In the output window it shows errors properly, and VS opens a correct file/line when clicked. But there's "error list" window in VS as well, and for some reason those errors don't propagate there. I see only one build error like below. Without error list some keyboard shortcuts (next/prev error for example) don't work properly. 

Error		cd ~/projects/linux_test;./a.sh 2>&1|MSVC_DIR='c:\Users\dixon\Documents\Visual Studio 2017\Projects\linux_test\linux_test\' gcc2vs exited with code 1, please see the Output Window - Build output for more details (NOTE: the build output verbosity might need to be changed in Tools Options to see more information in the Output Window).	linux_test	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.Makefile.Targets	135

**Comment by jwt27** [comment]
Ha, you're telling me! Better keep bugging Microsoft about it.
The odd thing is that this used to work with plain makefile projects, but no longer does after installing the VSLinux extension.

**Comment by jwt27** [comment]
Closing since this was fixed a while back in VS2017.
