### ISSUE TITLE
libgcc_2_seh-1.dll

### ISSUE THREAD

**Issue by M0ntage** [jwt27/gcc2vs#2]
I get the error 
"/cygdrive/c/gcc2vs/gcc2vs.exe: error while loading shared libraries: libgcc_s_seh-1.dll: cannot open shared object file: No such file or directory"

Since we are building for NIOS II, we use cygwin build scripts.

I downloaded the dll (I hope), put it in the same folder as this .exe, and it stopped complaining! The only problem being that I no longer see the errors, as if gcc2vs is filtering them out.

This is what I have put in our build scripts.
%.o: %.c
	@$(ECHO) Compiling $(<F)...
	$(CC) -xc -MP -MD -MMD -c -pipe -O0 -g -Wall -mhw-div -mhw-mul -mno-hw-mulx $(CFLAGS) $(ALT_CFLAGS) $(CFLAGS) -o $@ $^ 2>&1 | gcc2vs

Am I doing this completely wrong? Does your program only work if I use the visual studio makefile system?

**Comment by jwt27** [comment]
Hi there,
First of all, I've only used this with msys2/mingw, so I can't say if it should work on cygwin. I'm not sure about the exact differences between the two, but I imagine the directory resolving might work a bit differently, for one.

The missing DLL is required for c++ exception handling on Windows. You could try compiling with `-fno-exceptions`, or static linking to remove the dependency. Although I'm quite sure this dll should come pre-installed with cygwin.

And obviously gcc2vs shouldn't be filtering out errors, that would defeat its whole purpose. Does it filter out everything from gcc, or just the errors and warnings? If you run a simple C++ hello world program, do you get any output at all?

**Comment by jwt27** [comment]
Stale issue, closing.
